/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/YzSDAAP4fM5
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { CardContent, Card, CardTitle, CardHeader } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function taskdash() {
  return (
    (<div key="1" className="flex flex-col min-h-screen w-full">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <Link className="items-center gap-2 text-lg font-semibold md:gap-2" href="#">
          <Package2Icon className="h-6 w-6" />
          <span className="sr-only">Acme Inc</span>
        </Link>
        <nav className="flex flex-1 items-center gap-4 md:ml-6">
          <Link className="font-bold" href="#">
            Home
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Tasks
          </Link>
          <Link className="text-gray-500 dark:text-gray-400" href="#">
            Projects
          </Link>
        </nav>
        <Button className="rounded-full ml-auto md:hidden" size="icon" variant="outline">
          <SearchIcon className="h-4 w-4" />
          <span className="sr-only">Search</span>
        </Button>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
              size="icon"
              variant="ghost">
              <img
                alt="Avatar"
                className="rounded-full"
                height="32"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "32/32",
                  objectFit: "cover",
                }}
                width="32" />
              <span className="sr-only">Toggle user menu</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>My Account</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Support</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <div className="flex-1 flex flex-col p-4 md:p-6">
        <div className="flex items-center gap-4 md:gap-2">
          <Button size="icon" variant="outline">
            <ArrowLeftIcon className="h-4 w-4" />
            <span className="sr-only">Back</span>
          </Button>
          <h1 className="font-semibold text-lg md:text-xl">Tasks</h1>
          <Button className="ml-auto" size="sm" variant="outline">
            Add task
          </Button>
        </div>
        <div className="flex flex-col min-h-screen w-full">
          <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
            <Link className="items-center gap-2 text-lg font-semibold md:gap-2" href="#">
              <Package2Icon className="h-6 w-6" />
              <span className="sr-only">Acme Inc</span>
            </Link>
            <nav className="flex flex-1 items-center gap-4 md:ml-6">
              <Link className="font-bold" href="#">
                Home
              </Link>
              <Link className="text-gray-500 dark:text-gray-400" href="#">
                Tasks
              </Link>
              <Link className="text-gray-500 dark:text-gray-400" href="#">
                Projects
              </Link>
            </nav>
            <Button className="rounded-full ml-auto md:hidden" size="icon" variant="outline">
              <SearchIcon className="h-4 w-4" />
              <span className="sr-only">Search</span>
            </Button>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800"
                  size="icon"
                  variant="ghost">
                  <img
                    alt="Avatar"
                    className="rounded-full"
                    height="32"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "32/32",
                      objectFit: "cover",
                    }}
                    width="32" />
                  <span className="sr-only">Toggle user menu</span>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuLabel>My Account</DropdownMenuLabel>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Settings</DropdownMenuItem>
                <DropdownMenuItem>Support</DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem>Logout</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </header>
          <div className="flex-1 flex flex-col p-4 md:p-6">
            <div className="flex items-center gap-4 md:gap-2">
              <Button size="icon" variant="outline">
                <ArrowLeftIcon className="h-4 w-4" />
                <span className="sr-only">Back</span>
              </Button>
              <h1 className="font-semibold text-lg md:text-xl">Tasks</h1>
              <Button className="ml-auto" size="sm" variant="outline">
                Add task
              </Button>
            </div>
            <div className="grid gap-4 mt-4 md:grid-cols-3">
              <Card>
                <CardContent className="flex flex-col justify-center p-6">
                  <div className="text-3xl font-bold">23</div>
                  <div className="text-sm text-gray-500 dark:text-gray-400">Total Tasks</div>
                </CardContent>
              </Card>
              <div className="md:col-span-2">
                <Card>
                  <CardContent className="flex flex-col justify-center p-6">
                    <div className="text-3xl font-bold">8</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Pending Tasks</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="flex flex-col justify-center p-6">
                    <div className="text-3xl font-bold">5</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Completed Tasks</div>
                  </CardContent>
                </Card>
                <Card>
                  <CardContent className="flex flex-col justify-center p-6">
                    <div className="text-3xl font-bold">10</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">Tasks In Progress</div>
                  </CardContent>
                </Card>
              </div>
            </div>
            <Card className="mt-4">
              <CardHeader className="border-b">
                <CardTitle>Tasks</CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="grid gap-1 text-sm">
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Reorder the task list
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Create Wireframes
                    <Badge
                      className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-500">
                      2
                    </Badge>
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Review PR#123
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Call with client
                    <Badge
                      className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-green-500">
                      done
                    </Badge>
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Send report
                    <Badge
                      className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-400">
                      late
                    </Badge>
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Schedule meeting with team
                    <Badge
                      className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-yellow-500">
                      today
                    </Badge>
                  </Link>
                  <Link
                    className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                    href="#">
                    <ChevronRightIcon className="h-4 w-4" />
                    Update project timeline
                    <Badge
                      className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-400">
                      pending
                    </Badge>
                  </Link>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <Card className="mt-4">
          <CardHeader className="border-b">
            <CardTitle>Tasks</CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <div className="grid gap-1 text-sm">
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Reorder the task list
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Create Wireframes
                <Badge
                  className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-500">
                  2
                </Badge>
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Review PR#123
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Call with client
                <Badge
                  className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-green-500">
                  done
                </Badge>
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Send report
                <Badge
                  className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-400">
                  late
                </Badge>
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Schedule meeting with team
                <Badge
                  className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-yellow-500">
                  today
                </Badge>
              </Link>
              <Link
                className="flex items-center gap-2 p-3 hover:bg-gray-100 rounded-md dark:hover:bg-gray-800"
                href="#">
                <ChevronRightIcon className="h-4 w-4" />
                Update project timeline
                <Badge
                  className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gray-400">
                  pending
                </Badge>
              </Link>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>)
  );
}

function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function ChevronRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>)
  );
}


function Package2Icon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}
